source 'https://rubygems.org'

# You may use http://rbenv.org/ or https://rvm.io/ to install and use this version
ruby ">= 2.6.10"

# CocoaPods 1.16.2 requires xcodeproj 1.27+ for current Xcode project
# generation fixes.
gem 'cocoapods', '~> 1.16', '>= 1.16.2'
gem 'activesupport', '>= 6.1.7.5', '< 8'
gem 'xcodeproj', '>= 1.27.0', '< 2.0'

# Ruby 3.4.0 has removed some libraries from the standard library.
gem 'bigdecimal'
gem 'logger'
gem 'benchmark'
gem 'mutex_m'
gem 'nkf'
