//
//  TestHybridObjectSpec.swift
//  NitroModules
//
//  Created by Marc Rousavy on 17.07.24.
//

import Foundation

// Generated by Nitrogen (Swift protocol spec)
public protocol SwiftTestHybridObjectSpec {
  var hybridContext: margelo.HybridContext { get set }
  
  var int: Int { get set }
  
  func throwError() throws -> Int
  
  func asyncMethod() async -> Double
}
