// swift-tools-version: 6.0
///
/// Package.swift
/// This file was generated by nitrogen. DO NOT MODIFY THIS FILE.
/// https://github.com/mrousavy/nitro
/// Copyright © Marc Rousavy @ Margelo
///
//
// React Native SwiftPM manifest for NitroTest. Consumed by RN's
// SwiftPM autolinking as a "self-managed" package through the
// <app>/ios/build/generated/autolinking/libs/NitroTest/ symlink — the
// relative package paths below resolve against that symlink location:
//   ../../../../xcframeworks -> <app>/ios/build/xcframeworks (ReactNative)
//   ../NitroModules          -> libs/NitroModules (nitro core)
//
// NOTE: these path references assume React Native SwiftPM's default
// local-artifacts mode (xcframeworks downloaded into <app>/ios/build/).
// RN's experimental remote-package mode (RN_SPM_REMOTE_URL) is not yet
// supported by generated Nitro manifests.
//

import PackageDescription

let reactCxxDefines: [CXXSetting] = [
    // Match the prebuilt React.framework's config-gated C++ ABI.
    .define("DEBUG", .when(configuration: .debug)),
    .define("NDEBUG", .when(configuration: .release)),
    // React Native's prebuilt SwiftPM distribution is New Architecture only.
    .define("RCT_NEW_ARCH_ENABLED", to: "1"),
]

let headerDirs: [CXXSetting] = [
    .headerSearchPath("cpp"),
    .headerSearchPath("nitrogen/generated/shared/c++"),
    .headerSearchPath("nitrogen/generated/shared/c++/views"),
    .headerSearchPath("nitrogen/generated/ios"),
    .headerSearchPath("nitrogen/generated/ios/c++"),
    .headerSearchPath("nitrogen/generated/ios/c++/views"),
]

let package = Package(
    name: "ReactNativeNitroTest",
    platforms: [.iOS(.v15), .visionOS(.v1)],
    products: [
        // Only the root of the target chain is vended - SwiftPM pulls
        // NitroTest (Swift) and NitroTestCore (C++) in as its target
        // dependencies, propagating their module, public headers and objects
        // to dependents. Naming them here would add nothing.
        .library(name: "ReactNativeNitroTest", targets: ["NitroTestSwiftBridge"]),
    ],
    dependencies: [
        .package(name: "ReactNative", path: "../../../../xcframeworks"),
        .package(name: "NitroModules", path: "../NitroModules"),
        .package(name: "ReactNativeNitroTestExternal", path: "../ReactNativeNitroTestExternal"),
    ],
    targets: [
        // C++ layer: nitrogen's cross-platform specs + the user's C++ hybrids.
        // No Swift dependency — this is what the Swift target imports.
        .target(
            name: "NitroTestCore",
            dependencies: [
                .product(name: "NitroModules", package: "NitroModules"),
                .product(name: "ReactNativeNitroTestExternal", package: "ReactNativeNitroTestExternal"),
                .product(name: "ReactHeaders", package: "ReactNative"),
                .product(name: "ReactNativeHeaders", package: "ReactNative"),
                .product(name: "ReactNativeDependenciesHeaders", package: "ReactNative"),
            ],
            path: ".",
            sources: [
                "nitrogen/generated/shared/c++",
            ],
            publicHeadersPath: "nitrogen/generated/include",
            cxxSettings: headerDirs + reactCxxDefines
        ),
        // Swift layer: nitrogen's Swift specs/_cxx bridges + user Swift hybrids.
        .target(
            name: "NitroTest",
            dependencies: [
                "NitroTestCore",
                .product(name: "NitroModules", package: "NitroModules"),
                .product(name: "ReactNativeNitroTestExternal", package: "ReactNativeNitroTestExternal"),
            ],
            path: ".",
            sources: [
                "ios/HybridBase.swift",
                "ios/HybridChild.swift",
                "ios/HybridPlatformObject.swift",
                "ios/HybridRecyclableTestView.swift",
                "ios/HybridSomeInternalObject.swift",
                "ios/HybridTestObjectSwift.swift",
                "ios/HybridTestView.swift",
                "nitrogen/generated/ios/swift",
                "nitrogen/generated/ios/NitroTestAutolinking.swift",
            ],
            swiftSettings: [
                .interoperabilityMode(.Cxx),
                .swiftLanguageMode(.v5),
            ]
        ),
        // SwiftBridge layer: every C++/ObjC++ TU that consumes the Swift-generated
        // interface header (NitroTest-Swift.h). Structurally required:
        // these TUs cannot live in NitroTestCore (Core -> Swift -> Core
        // cycle) nor in the Swift target (SwiftPM forbids mixed languages).
        .target(
            name: "NitroTestSwiftBridge",
            dependencies: [
                "NitroTest",
                "NitroTestCore",
                .product(name: "NitroModules", package: "NitroModules"),
                .product(name: "ReactNativeNitroTestExternal", package: "ReactNativeNitroTestExternal"),
                .product(name: "ReactHeaders", package: "ReactNative"),
                .product(name: "ReactNativeHeaders", package: "ReactNative"),
                .product(name: "ReactNativeDependenciesHeaders", package: "ReactNative"),
            ],
            path: ".",
            sources: [
                "cpp/HybridTestObjectCpp.cpp",
                "nitrogen/generated/ios/c++",
                "nitrogen/generated/ios/NitroTest-Swift-Cxx-Bridge.cpp",
                "nitrogen/generated/ios/NitroTestAutolinking.mm",
            ],
            publicHeadersPath: "nitrogen/generated/include-bridge",
            cxxSettings: headerDirs + reactCxxDefines + [
                // Under Xcode, React Native's SPM sync symlinks
                // $OBJROOT/GeneratedModuleMaps-<platform> (where Xcode stages
                // the Swift-generated NitroTest-Swift.h) to this stable
                // path, so the Swift-Cxx umbrella can include it TEXTUALLY.
                // Under `swift build` SwiftPM vends the header natively and
                // this path simply doesn't exist.
                .headerSearchPath(".spm-derived-headers"),
            ],
            linkerSettings: [
                .linkedFramework("Foundation"),
                .linkedFramework("UIKit", .when(platforms: [.iOS])),
            ]
        ),
    ],
    cxxLanguageStandard: .cxx20
)
