name: ðŸ’… Nitrogen error
description: File a bug report that occurred when running nitrogen
labels: [nitrogen]
body:
  - type: textarea
    attributes:
      label: What happened?
      description: Explain what exactly happened and what steps you took.
      placeholder: I created my spec, and nitrogen says it cannot find any specs.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Nitrogen CLI logs (with `--logLevel="debug"`)
      description: Share the full logs that appear in the console when running nitrogen with the `--logLevel="debug"` flag.
      render: tsx
      placeholder: >
        $ npx nitrogen --logLevel="debug"

        ðŸ”§  Loading nitro.json config...

        ðŸš€  Nitrogen runs at ~/Projects/react-native-nitro/packages/...
            ðŸ”  Nitrogen found 3 specs in ./src/specs
        â³  Parsing Math.nitro.ts...

        ...
    validations:
      required: true
  - type: textarea
    attributes:
      label: Nitro Specs (`.nitro.ts`)
      description: Share your Nitro specs (`.nitro.ts` files), ideally stripped down to the core problem so I can reproduce this myself locally.
      render: ts
      placeholder: >
        interface Math extends HybridObject<{ ios: 'c++' }> {
          // ...
        }
    validations:
  - type: input
    attributes:
      label: Nitro Modules Version
      description: Which version of react-native-nitro-modules are you using?
      placeholder: ex. 0.31.0
    validations:
      required: true
  - type: input
    attributes:
      label: Nitrogen Version
      description: Which version of nitrogen are you using?
      placeholder: ex. 0.31.0
    validations:
      required: true
  - type: dropdown
    attributes:
      label: Operating system
      description: Select your operating system that you are trying to build on.
      multiple: true
      options:
        - MacOS
        - Windows
        - Linux
    validations:
      required: true
  - type: checkboxes
    attributes:
      label: Additional information
      description: Please check all the boxes that apply
      options:
        - label: I have read and followed the [Troubleshooting Guide](https://nitro.margelo.com/docs/troubleshooting).
          required: true
        - label: I created a reproduction PR to reproduce this issue here in the nitro repo. (See [Contributing](https://nitro.margelo.com/docs/contributing) for more information)
        - label: I searched for [similar issues in this repository](https://github.com/mrousavy/nitro/issues) and found none.
          required: true
