///
/// NitroModules-Swift-Cxx-Bridge.hpp
/// Copyright © Marc Rousavy @ Margelo
///

#pragma once

namespace NitroModules {
  class AnyMap;
}

#include "ArrayBufferHolder.hpp"

#if __has_include("NitroModules-Swift.h")
// This header is generated by Xcode/Swift on every app build.
#include "NitroModules-Swift.h"
// Same as above, but used when building with frameworks (`use_frameworks`)
#elif __has_include(<NitroModules/NitroModules-Swift.h>)
#include <NitroModules/NitroModules-Swift.h>
#else
// TODO: This should be an error and use_frameworks! should not be required.
#error NitroModules's autogenerated Swift header cannot be found! Make sure you enabled use_frameworks!
#endif
