import fs from 'fs'
import path from 'path'
import type { Autolinking } from './Autolinking.js'
import { createHybridObjectIntializer } from './ios/createHybridObjectInitializer.js'
import { createPackageSwift } from './ios/createPackageSwift.js'
import { createPodspecRubyExtension } from './ios/createPodspecRubyExtension.js'
import { createSwiftCxxBridge } from './ios/createSwiftCxxBridge.js'
import { createSwiftUmbrellaHeader } from './ios/createSwiftUmbrellaHeader.js'
import { getSpmPackageName } from './ios/getSpmPackageName.js'

interface IOSAutolinking extends Autolinking {}

/**
 * Deletes a previously generated `Package.swift` when one can no longer be
 * generated (e.g. the package has no readable `package.json`).
 *
 * Nitrogen's own dangling-file cleanup only covers `nitrogen/generated/`, and
 * `Package.swift` lives at the PACKAGE ROOT — so without this it would linger
 * and keep React Native's SwiftPM autolinking treating the module as a
 * self-managed package.
 *
 * Only removes files carrying nitrogen's generated-by marker: a hand-authored
 * `Package.swift` (a library shipping its own SwiftPM support) is never
 * touched.
 */
function removeGeneratedPackageSwift(): void {
  const manifest = path.join(process.cwd(), 'Package.swift')
  try {
    if (!fs.existsSync(manifest)) return
    const content = fs.readFileSync(manifest, 'utf8')
    if (!content.includes('This file was generated by nitrogen')) return
    fs.rmSync(manifest)
  } catch {
    // Best-effort: a stale manifest is not worth failing codegen over.
  }
}

export function createIOSAutolinking(outputDirectory: string): IOSAutolinking {
  const podspecExtension = createPodspecRubyExtension()
  const swiftCxxBridge = createSwiftCxxBridge()
  const swiftUmbrellaHeader = createSwiftUmbrellaHeader()
  const hybridObjectInitializer = createHybridObjectIntializer()
  // React Native SwiftPM (Preview) support. Purely additive — CocoaPods apps
  // never read Package.swift — and needs no configuration: the package
  // identity is derived from the npm package name exactly as React Native's
  // autolinker derives it.
  const spmPackageName = getSpmPackageName(process.cwd())
  const packageSwift =
    spmPackageName != null
      ? createPackageSwift(spmPackageName, outputDirectory)
      : []
  // Also covers the case where a manifest cannot be expressed for this output
  // directory - see `createPackageSwift`.
  if (packageSwift.length === 0) removeGeneratedPackageSwift()

  return {
    platform: 'ios',
    sourceFiles: [
      podspecExtension,
      ...swiftCxxBridge,
      swiftUmbrellaHeader,
      ...hybridObjectInitializer,
      ...packageSwift,
    ],
  }
}
