import { NitroConfig } from '../../config/NitroConfig.js'
import { createCppHybridObjectRegistration } from '../../syntax/c++/CppHybridObjectRegistration.js'
import { includeHeader } from '../../syntax/c++/includeNitroHeader.js'
import { createFileMetadataString } from '../../syntax/helpers.js'
import type { SourceFile, SourceImport } from '../../syntax/SourceFile.js'
import { createSwiftHybridObjectRegistration } from '../../syntax/swift/SwiftHybridObjectRegistration.js'
import { indent } from '../../utils.js'
import { getUmbrellaHeaderName } from './createSwiftUmbrellaHeader.js'

type ObjcFile = Omit<SourceFile, 'language'> & { language: 'objective-c++' }
type SwiftFile = Omit<SourceFile, 'language'> & { language: 'swift' }

export function createHybridObjectIntializer(): [ObjcFile, SwiftFile] | [] {
  const autolinkingClassName = `${NitroConfig.current.getIosModuleName()}Autolinking`
  const umbrellaHeaderName = getUmbrellaHeaderName()
  const bridgeNamespace = NitroConfig.current.getSwiftBridgeNamespace('swift')

  const autolinkedHybridObjects =
    NitroConfig.current.getAutolinkedHybridObjects()

  const swiftRegistrations: string[] = []
  const cppRegistrations: string[] = []
  const cppImports: SourceImport[] = []
  let containsSwiftObjects = false
  for (const hybridObjectName of Object.keys(autolinkedHybridObjects)) {
    const config = autolinkedHybridObjects[hybridObjectName]

    if (config?.cpp != null) {
      // Autolink a C++ HybridObject!
      const { cppCode, requiredImports } = createCppHybridObjectRegistration({
        hybridObjectName: hybridObjectName,
        cppClassName: config.cpp,
      })
      cppImports.push(...requiredImports)
      cppRegistrations.push(cppCode)
    }
    if (config?.swift != null) {
      // Autolink a Swift HybridObject!
      containsSwiftObjects = true
      const { cppCode, requiredImports, swiftRegistrationClass } =
        createSwiftHybridObjectRegistration({
          hybridObjectName: hybridObjectName,
          swiftClassName: config.swift,
        })
      cppImports.push(...requiredImports)
      cppRegistrations.push(cppCode)
      swiftRegistrations.push(swiftRegistrationClass)
    }
  }

  if (cppRegistrations.length === 0) {
    // Nothing to autolink!
    return []
  }

  const umbrellaImport = containsSwiftObjects
    ? `#import "${umbrellaHeaderName}"`
    : ''
  const imports = cppImports.map((i) => includeHeader(i, true)).join('\n')

  const objcCode = `
${createFileMetadataString(`${autolinkingClassName}.mm`)}

#import <Foundation/Foundation.h>
#import <NitroModules/HybridObjectRegistry.hpp>
${umbrellaImport}
#import <type_traits>

${imports}

@interface ${autolinkingClassName} : NSObject
@end

@implementation ${autolinkingClassName}

+ (void) load {
  using namespace margelo::nitro;
  using namespace ${NitroConfig.current.getCxxNamespace('c++')};

  ${indent(cppRegistrations.join('\n'), '  ')}
}

@end
  `.trim()

  const swiftCode = `
${createFileMetadataString(`${autolinkingClassName}.swift`)}

import NitroModules

public final class ${autolinkingClassName} {
  public typealias bridge = ${bridgeNamespace}

  protocol AutolinkedClass {
    associatedtype T
    /**
     * Creates an instance of the Swift class that implements the HybridObject's spec,
     * and wraps it in a Swift class that can directly interop with C++.
     *
     * This is generated by Nitrogen and will initialize the class specified
     * in the \`"autolinking"\` property of \`nitro.json\`.
     */
    static func create() -> T
    /**
     * Returns whether this concrete implementation is also
     * conforming to the \`RecyclableView\` protocol, or not.
     */
    static var isRecyclableHybridView: Bool { get }
  }

  ${indent(swiftRegistrations.join('\n\n'), '  ')}
}
  `.trim()

  return [
    {
      content: objcCode,
      language: 'objective-c++',
      name: `${autolinkingClassName}.mm`,
      platform: 'ios',
      subdirectory: [],
    },
    {
      content: swiftCode,
      language: 'swift',
      name: `${autolinkingClassName}.swift`,
      platform: 'ios',
      subdirectory: [],
    },
  ]
}
