import { NitroConfig } from "../../config/NitroConfig.js";
import { createFileMetadataString } from "../../syntax/helpers.js";
import type { SourceFile } from "../../syntax/SourceFile.js";

export interface RubyFile extends Omit<SourceFile, "language"> {
  language: "ruby";
}

export function createPodspecRubyExtension(): RubyFile {
  const name = NitroConfig.current.getIosModuleName();
  const autolinkedHybridObjects =
    NitroConfig.current.getAutolinkedHybridObjects();
  const hasRust = Object.values(autolinkedHybridObjects).some(
    (config) => config?.rust != null,
  );

  const code = `
${createFileMetadataString(`${name}+autolinking.rb`, "#")}

# This is a Ruby script that adds all files generated by Nitrogen
# to the given podspec.
#
# To use it, add this to your .podspec:
# \`\`\`ruby
# Pod::Spec.new do |spec|
#   # ...
#
#   # Add all files generated by Nitrogen
#   load 'nitrogen/generated/ios/${name}+autolinking.rb'
#   add_nitrogen_files(spec)
# end
# \`\`\`

def add_nitrogen_files(spec)
  Pod::UI.puts "[NitroModules] 🔥 ${name} is boosted by nitro!"

  spec.dependency "NitroModules"

  current_source_files = Array(spec.attributes_hash['source_files'])
  spec.source_files = current_source_files + [
    # Generated cross-platform specs
    "nitrogen/generated/shared/**/*.{h,hpp,c,cpp,swift}",
    # Generated bridges for the cross-platform specs
    "nitrogen/generated/ios/**/*.{h,hpp,c,cpp,mm,swift}",
  ]

  current_public_header_files = Array(spec.attributes_hash['public_header_files'])
  spec.public_header_files = current_public_header_files + [
    # Generated specs
    "nitrogen/generated/shared/**/*.{h,hpp}",
    # Swift to C++ bridging helpers
    "nitrogen/generated/ios/${name}-Swift-Cxx-Bridge.hpp"
  ]

  current_private_header_files = Array(spec.attributes_hash['private_header_files'])
  spec.private_header_files = current_private_header_files + [
    # iOS specific specs
    "nitrogen/generated/ios/c++/**/*.{h,hpp}",
    # Views are framework-specific and should be private
    "nitrogen/generated/shared/**/views/**/*"
  ]

  current_pod_target_xcconfig = spec.attributes_hash['pod_target_xcconfig'] || {}
  spec.pod_target_xcconfig = current_pod_target_xcconfig.merge({
    # Use C++ 20
    "CLANG_CXX_LANGUAGE_STANDARD" => "c++20",
    # Enables C++ <-> Swift interop (by default it's only ObjC)
    "SWIFT_OBJC_INTEROP_MODE" => "objcxx",
    # Enables stricter modular headers
    "DEFINES_MODULE" => "YES",
  })
${
  hasRust
    ? `
  # Build and link the Rust static library.
  # cargo is invoked automatically as a script phase before compilation.
  rust_src_dir = File.join(__dir__, '..', 'shared', 'rust')
  rust_lib_dir = ENV['NITRO_RUST_LIB_DIR'] || File.join(rust_src_dir, 'target')

  spec.script_phases = [{
    :name => 'Build Rust Library',
    :script => %Q{
      set -e
      RUST_SRC_DIR="#{rust_src_dir}"
      RUST_LIB_DIR="#{rust_lib_dir}"

      # Determine Rust target triple from Xcode build settings
      if [ "$PLATFORM_NAME" = "iphonesimulator" ]; then
        if [ "$ARCHS" = "x86_64" ]; then
          RUST_TARGET="x86_64-apple-ios"
        else
          RUST_TARGET="aarch64-apple-ios-sim"
        fi
      elif [ "$PLATFORM_NAME" = "macosx" ]; then
        if [ "$ARCHS" = "x86_64" ]; then
          RUST_TARGET="x86_64-apple-darwin"
        else
          RUST_TARGET="aarch64-apple-darwin"
        fi
      else
        RUST_TARGET="aarch64-apple-ios"
      fi

      if ! command -v cargo &> /dev/null; then
        export PATH="$HOME/.cargo/bin:$PATH"
      fi

      echo "Building Rust library for $RUST_TARGET..."
      cd "$RUST_SRC_DIR"
      cargo build --release --target "$RUST_TARGET"

      # Copy the built library to the expected location
      mkdir -p "$RUST_LIB_DIR"
      cp "target/$RUST_TARGET/release/lib*.a" "$RUST_LIB_DIR/" 2>/dev/null || true
    },
    :execution_position => :before_compile,
    :shell_path => '/bin/sh',
  }]

  current_vendored_libraries = Array(spec.attributes_hash['vendored_libraries'])
  spec.vendored_libraries = current_vendored_libraries + [
    File.join(rust_lib_dir, "lib${name}_rust.a")
  ]
`
    : ""
}end
  `.trim();
  return {
    content: code,
    language: "ruby",
    name: `${name}+autolinking.rb`,
    platform: "ios",
    subdirectory: [],
  };
}
