import { NitroConfig } from '../../config/NitroConfig.js'
import {
  createFileMetadataString,
  isCppFile,
  isNotDuplicate,
} from '../../syntax/helpers.js'
import type { SourceFile } from '../../syntax/SourceFile.js'
import { indent } from '../../utils.js'
import { getWindowsAutolinkingClassName } from './createHybridObjectInitializer.js'

export interface MsBuildFile extends Omit<SourceFile, 'language'> {
  language: 'msbuild'
}

function toWindowsPath(path: string): string {
  return path.replace(/\//g, '\\')
}

function generatedPath(...segments: string[]): string {
  return '$(NitrogenGeneratedDir)' + toWindowsPath(segments.join('/'))
}

function getGeneratedPath(file: SourceFile): string {
  return generatedPath(
    file.platform,
    file.language,
    ...file.subdirectory,
    file.name
  )
}

export function createMsBuildExtension(
  files: SourceFile[],
  hasAutolinkedHybridObjects: boolean
): MsBuildFile {
  const name = NitroConfig.current.getWindowsModuleName()
  const autolinkingClassName = getWindowsAutolinkingClassName()

  const sourceFiles = files
    .filter((f) => f.platform === 'shared' && isCppFile(f))
    .map((f) => getGeneratedPath(f))
    .filter(isNotDuplicate)

  if (hasAutolinkedHybridObjects) {
    sourceFiles.push(generatedPath('windows', `${autolinkingClassName}.cpp`))
  }

  const clCompiles = sourceFiles
    .map((f) => `<ClCompile Include="${f}" />`)
    .join('\n')

  const code = `
<?xml version="1.0" encoding="utf-8"?>
<!--
${createFileMetadataString(`${name}+autolinking.props`, '#').replace(/^#[ ]?/gm, '  ')}

  This is an MSBuild property sheet that adds all files generated by Nitrogen to
  the current Visual C++ project.

  To use it, add this to your .vcxproj (after the Microsoft.Cpp.props import):
  <Import Project="$(MSBuildThisFileDirectory)..\\nitrogen\\generated\\windows\\${name}+autolinking.props" />
-->
<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <PropertyGroup>
    <NitrogenGeneratedDir>$(MSBuildThisFileDirectory)..\\</NitrogenGeneratedDir>
    <!--
      Expose the generated headers to every project that references this one -
      that includes the app itself, so it can use the generated types directly.
    -->
    <PublicIncludeDirectories>
      $(NitrogenGeneratedDir)shared\\c++;
      $(NitrogenGeneratedDir)windows;
      $(PublicIncludeDirectories)
    </PublicIncludeDirectories>
  </PropertyGroup>

  <ItemDefinitionGroup>
    <ClCompile>
      <AdditionalIncludeDirectories>$(NitrogenGeneratedDir)shared\\c++;$(NitrogenGeneratedDir)windows;%(AdditionalIncludeDirectories)</AdditionalIncludeDirectories>
      <!-- Nitro requires C++20, and its generated specs produce large object files. -->
      <LanguageStandard>stdcpp20</LanguageStandard>
      <AdditionalOptions>%(AdditionalOptions) /bigobj</AdditionalOptions>
      <ExceptionHandling>Sync</ExceptionHandling>
    </ClCompile>
  </ItemDefinitionGroup>

  <!-- All C++ sources that were generated by Nitrogen -->
  <ItemGroup>
    ${indent(clCompiles, '    ')}
  </ItemGroup>
</Project>
  `.trim()

  return {
    content: code,
    language: 'msbuild',
    name: `${name}+autolinking.props`,
    platform: 'windows',
    subdirectory: [],
  }
}
