import type { PlatformSpec } from 'react-native-nitro-modules'
import type { Language, Platform } from './getPlatformSpecs.js'
import {
  Type,
  type InterfaceDeclaration,
  type MethodSignature,
  type ParameterDeclaration,
  type PropertySignature,
} from 'ts-morph'
import { ts } from 'ts-morph'
import { getNodeName } from './getNodeName.js'

interface File {
  name: string
  content: string
  language: Language
}

interface CodeNode {
  /**
   * Get the code of this code node (e.g. property, method) in the given language.
   */
  getCode(language: Language): string
  /**
   * Get all extra definition files this code node needs (e.g. extra type/struct declarations
   * for complex types), or `[]` if none are required (e.g. if this uses primitive types only)
   */
  getDefinitionFiles(language: Language): File[]
}

function createFileMetadataString(filename: string): string {
  const now = new Date()
  return `
///
/// ${filename}
/// ${now.toDateString()}
/// This file was generated by nitrogen. DO NOT MODIFY THIS FILE.
/// https://github.com/mrousavy/react-native-nitro
/// Copyright © ${now.getFullYear()} Marc Rousavy @ Margelo
///
`
}

function capitalizeName(name: string): string {
  return name.charAt(0).toUpperCase() + name.slice(1)
}

function joinToIndented(array: string[], indentation: string = '    '): string {
  return array.join('\n').replaceAll('\n', `\n${indentation}`)
}

interface CppMethodSignature {
  returnType: TSType | VoidType
  parameters: NamedTSType[]
  rawName: string
  name: string
  type: 'getter' | 'setter' | 'method'
}

class VoidType implements CodeNode {
  constructor() {}

  getCode(): string {
    return 'void'
  }

  getDefinitionFiles(): File[] {
    return []
  }
}

class TSType implements CodeNode {
  readonly type: Type
  readonly isOptional: boolean
  readonly kind: 'primitive' | 'complex'
  private readonly cppName: string
  private readonly extraFiles: File[]

  private readonly baseTypes: TSType[]
  private readonly referencedTypes: TSType[]

  constructor(type: Type, isOptional: boolean) {
    this.type = type
    this.isOptional = isOptional
    this.baseTypes = []
    this.referencedTypes = []
    this.extraFiles = []

    if (type.isBigInt()) {
      this.cppName = 'int64_t'
      this.kind = 'primitive'
    } else if (type.isBoolean()) {
      this.cppName = 'bool'
      this.kind = 'primitive'
    } else if (type.isNull() || type.isUndefined()) {
      this.cppName = 'std::nullptr_t'
      this.kind = 'primitive'
    } else if (type.isNumber()) {
      this.cppName = 'double'
      this.kind = 'primitive'
    } else if (type.isString()) {
      this.cppName = 'std::string'
      this.kind = 'complex'
    } else if (type.isVoid()) {
      this.cppName = 'void'
      this.kind = 'primitive'
    } else if (type.isObject() || type.isInterface()) {
      // It references another interface/type, either a simple struct, or another HybridObject
      this.kind = 'complex'
      const typename = type.getText()

      const isHybridObject = type
        .getBaseTypes()
        .some((t) => t.getText().includes('HybridObject'))

      if (isHybridObject) {
        // It is another HybridObject being referenced!
        this.cppName = `std::shared_ptr<${typename}>`
      } else {
        // It is a simple struct being referenced.
        const cppProperties: NamedTSType[] = []
        for (const prop of type.getProperties()) {
          // recursively resolve types for each property of the referenced type
          const declaration = prop.getValueDeclarationOrThrow()
          const propType = prop.getTypeAtLocation(declaration)
          const refType = new NamedTSType(
            propType,
            prop.isOptional(),
            prop.getName()
          )
          cppProperties.push(refType)
          this.referencedTypes.push(refType)
        }
        const cppStructProps = cppProperties.map(
          (p) => `${p.getCode()} ${p.name};`
        )
        const cppFromJsiProps = cppProperties.map(
          (p) =>
            `.${p.name} = JSIConverter<${p.getCode()}>::fromJSI(runtime, obj.getProperty(runtime, "${p.name}")),`
        )
        const cppToJsiCalls = cppProperties.map(
          (p) =>
            `obj.setProperty(runtime, "${p.name}", JSIConverter<${p.getCode()}>::toJSI(runtime, arg.${p.name}));`
        )
        const cppCode = `
${createFileMetadataString(`${typename}.hpp`)}

#pragma once

#include <stddef.h>
#include <string.h>
#include <optional>
#include <NitroModules/JSIConverter.hpp>

struct ${typename} {
public:
  ${joinToIndented(cppStructProps, '  ')}
};

namespace margelo {

  // C++ ${typename} <> JS ${typename}
  template <> struct JSIConverter<${typename}> {
    static ${typename} fromJSI(jsi::Runtime& runtime, const jsi::Value& arg) {
      jsi::Object obj = arg.asObject(runtime);
      return ${typename} {
        ${joinToIndented(cppFromJsiProps, '        ')}
      };
    }
    static jsi::Value toJSI(jsi::Runtime& runtime, const ${typename}& arg) {
      jsi::Object obj(runtime);
      ${joinToIndented(cppToJsiCalls, '      ')}
      return obj;
    }
  };

} // namespace margelo
        `
        this.extraFiles.push({
          language: 'c++',
          name: `${typename}.hpp`,
          content: cppCode,
        })
        this.cppName = typename
      }
    } else {
      throw new Error(
        `The TypeScript type "${type.getText()}" cannot be represented in C++!`
      )
    }
  }

  getCode(): string {
    if (this.isOptional) {
      return `std::optional<${this.cppName}>`
    } else {
      return this.cppName
    }
  }

  getDefinitionFiles(): File[] {
    const extra = this.extraFiles
    const inheritedDefinitionFiles = this.baseTypes.flatMap((b) =>
      b.getDefinitionFiles()
    )
    const referencedDefinitionFiles = this.referencedTypes.flatMap((r) =>
      r.getDefinitionFiles()
    )
    return [...extra, ...inheritedDefinitionFiles, ...referencedDefinitionFiles]
  }
}

class NamedTSType extends TSType {
  readonly name: string

  constructor(type: Type, isOptional: boolean, name: string) {
    super(type, isOptional)
    this.name = name
  }
}

class Property implements CodeNode {
  readonly name: string
  readonly type: NamedTSType
  readonly isReadonly: boolean

  constructor(prop: PropertySignature) {
    this.name = prop.getName()
    this.isReadonly = prop.hasModifier(ts.SyntaxKind.ReadonlyKeyword)
    const type = prop.getTypeNodeOrThrow().getType()
    const isOptional = prop.hasQuestionToken() || type.isNullable()
    this.type = new NamedTSType(type, isOptional, this.name)
  }

  get cppSignatures(): CppMethodSignature[] {
    const signatures: CppMethodSignature[] = []
    const capitalizedName = capitalizeName(this.name)
    // getter
    signatures.push({
      returnType: this.type,
      rawName: this.name,
      name: `get${capitalizedName}`,
      parameters: [],
      type: 'getter',
    })
    if (!this.isReadonly) {
      // setter
      signatures.push({
        returnType: new VoidType(),
        rawName: this.name,
        name: `set${capitalizedName}`,
        parameters: [this.type],
        type: 'setter',
      })
    }
    return signatures
  }

  getDefinitionFiles(): File[] {
    return this.type.getDefinitionFiles()
  }

  getCode(language: Language): string {
    switch (language) {
      case 'c++':
        const signatures = this.cppSignatures
        const codeLines = signatures.map((s) => {
          const params = s.parameters.map((p) => {
            if (p.kind === 'complex') {
              // Complex types can be const& passed
              return `const ${p.getCode()}& ${p.name}`
            } else {
              // Primitive types are just passed by value
              return `${p.getCode()} ${p.name}`
            }
          })
          return `virtual ${s.returnType.getCode()} ${s.name}(${params.join(', ')}) = 0;`
        })
        return codeLines.join('\n')
      default:
        throw new Error(
          `Language ${language} is not yet supported for properties!`
        )
    }
  }
}

class Parameter implements CodeNode {
  readonly name: string
  readonly type: NamedTSType

  constructor(param: ParameterDeclaration) {
    this.name = param.getName()
    const type = param.getTypeNodeOrThrow().getType()
    const isOptional =
      param.hasQuestionToken() || param.isOptional() || type.isNullable()
    this.type = new NamedTSType(type, isOptional, this.name)
  }

  getCode(language: Language): string {
    switch (language) {
      case 'c++':
        return `${this.type.getCode()} ${this.name}`
      default:
        throw new Error(
          `Language ${language} is not yet supported for parameters!`
        )
    }
  }

  getDefinitionFiles(): File[] {
    return this.type.getDefinitionFiles()
  }
}

class Method implements CodeNode {
  readonly name: string
  readonly returnType: TSType
  readonly parameters: Parameter[]

  constructor(prop: MethodSignature) {
    this.name = getNodeName(prop)
    const returnType = prop.getReturnTypeNodeOrThrow()
    const type = returnType.getType()
    const isOptional = type.isNullable()
    this.returnType = new TSType(type, isOptional)
    this.parameters = prop.getParameters().map((p) => new Parameter(p))
  }

  get cppSignature(): CppMethodSignature {
    return {
      rawName: this.name,
      name: this.name,
      returnType: this.returnType,
      parameters: this.parameters.map((p) => p.type),
      type: 'method',
    }
  }

  getCode(language: Language): string {
    switch (language) {
      case 'c++':
        const signature = this.cppSignature
        const params = signature.parameters.map((p) => {
          if (p.kind === 'complex') {
            // Complex types can be const& passed
            return `const ${p.getCode()}& ${p.name}`
          } else {
            // Primitive types are just passed by value
            return `${p.getCode()} ${p.name}`
          }
        })
        return `virtual ${signature.returnType.getCode()} ${signature.name}(${params.join(', ')}) = 0;`
      default:
        throw new Error(
          `Language ${language} is not yet supported for property getters!`
        )
    }
  }

  getDefinitionFiles(): File[] {
    const parametersDefinitionFiles = this.parameters.flatMap((p) =>
      p.getDefinitionFiles()
    )
    const returnTypeDefinitionFiles = this.returnType.getDefinitionFiles()
    return [...returnTypeDefinitionFiles, ...parametersDefinitionFiles]
  }
}

export function createPlatformSpec<
  TPlatform extends Platform,
  TLanguage extends PlatformSpec[TPlatform],
>(
  module: InterfaceDeclaration,
  platform: TPlatform,
  language: TLanguage
): File[] {
  switch (platform) {
    case 'ios':
      switch (language) {
        case 'swift':
          return createAppleSwiftSpec(module)
        case 'c++':
          return createSharedCppSpec(module)
        default:
          throw new Error(`${language} is not supported on ${platform}!`)
      }
    case 'android':
      switch (language) {
        case 'kotlin':
          return createAndroidKotlinSpec(module)
        case 'c++':
          return createSharedCppSpec(module)
        default:
          throw new Error(`${language} is not supported on ${platform}!`)
      }
    default:
      throw new Error(`${platform} is not supported!`)
  }
}

function createSharedCppSpec(module: InterfaceDeclaration): File[] {
  const moduleName = getNodeName(module)
  const cppClassName = `${moduleName}Spec`

  // Properties (getters + setters)
  const properties = module
    .getChildrenOfKind(ts.SyntaxKind.PropertySignature)
    .filter((p) => p.getFirstChildByKind(ts.SyntaxKind.FunctionType) == null)
  const cppProperties = properties.map((p) => new Property(p))

  // Functions
  const functions = module.getChildrenOfKind(ts.SyntaxKind.MethodSignature)
  const cppMethods = functions.map((f) => new Method(f))

  // Generate the full header / code
  const cppHeaderCode = `
${createFileMetadataString(`${cppClassName}.hpp`)}

#pragma once

#include <stddef.h>
#include <string.h>
#include <NitroModules/HybridObject.hpp>

class ${cppClassName}: public HybridObject {
  public:
    // Constructor
    explicit ${cppClassName}(): HybridObject(TAG) { }

  public:
    // Properties
    ${joinToIndented(cppProperties.map((p) => p.getCode('c++')))}

  public:
    // Methods
    ${joinToIndented(cppMethods.map((m) => m.getCode('c++')))}

  protected:
    // Tag for logging
    static constexpr auto TAG = "${moduleName}";

  private:
    // Hybrid Setup
    void loadHybridMethods() override;
};
    `

  // Each C++ method needs to be registered in the HybridObject - that's getters, setters and normal methods.
  const registrations: string[] = []
  const signatures = [
    ...cppProperties.flatMap((p) => p.cppSignatures),
    ...cppMethods.map((m) => m.cppSignature),
  ]
  for (const signature of signatures) {
    let registerMethod: string
    switch (signature.type) {
      case 'getter':
        registerMethod = 'registerHybridGetter'
        break
      case 'setter':
        registerMethod = 'registerHybridSetter'
        break
      case 'method':
        registerMethod = 'registerHybridMethod'
        break
      default:
        throw new Error(`Invalid C++ Signature Type: ${signature.type}!`)
    }
    registrations.push(
      `${registerMethod}("${signature.rawName}", &${cppClassName}::${signature.name}, this);`
    )
  }

  const cppBodyCode = `
${createFileMetadataString(`${cppClassName}.cpp`)}

#include "${cppClassName}.hpp"

void ${cppClassName}::loadHybridMethods() {
  ${joinToIndented(registrations, '  ')}
}
    `

  const files: File[] = []
  files.push({
    content: cppHeaderCode,
    language: 'c++',
    name: `${cppClassName}.hpp`,
  })
  files.push({
    content: cppBodyCode,
    language: 'c++',
    name: `${cppClassName}.cpp`,
  })
  for (const prop of cppProperties) {
    // Add all files that the properties referenced
    for (const file of prop.getDefinitionFiles()) {
      files.push(file)
    }
  }
  for (const method of cppMethods) {
    // Add all files that the methods referenced
    for (const file of method.getDefinitionFiles()) {
      files.push(file)
    }
  }
  return files
}

function createAppleSwiftSpec(_module: InterfaceDeclaration): File[] {
  throw new Error(`Swift for Apple/iOS is not yet implemented!`)
}

function createAndroidKotlinSpec(_module: InterfaceDeclaration): File[] {
  throw new Error(`Kotlin for Android is not yet implemented!`)
}
