name: 'Update Lockfiles (bun.lock + Podfile.lock)'

on:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/update-lockfiles.yml"
  pull_request:
    paths:
      - ".github/workflows/update-lockfiles.yml"
      - "package.json"
      - "**/package.json"

permissions:
  contents: write

jobs:
  update-lockfiles:
    name: "Update lockfiles (Podfile.lock)"
    if: github.actor == 'dependabot[bot]'
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.ref }}

      - uses: oven-sh/setup-bun@v2

      - name: Setup Ruby (bundle)
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7.2
          bundler-cache: true
          working-directory: example/ios

      - name: Select Xcode 16.4
        run: sudo xcode-select -s "/Applications/Xcode_16.4.app/Contents/Developer"

      - run: |
          bun install

          cd example
          bundle install
          bun pods
          cd ..

          cd docs
          bun install
          cd ..

          git add bun.lock
          git add example/ios/Podfile.lock
          git add example/Gemfile.lock

          git config --global user.name 'dependabot[bot]'
          git config --global user.email 'dependabot[bot]@users.noreply.github.com'
          git commit --amend --no-edit
          git push --force
